name: Daily Update - Fetch Yesterday's Data

on:
  # 每天 UTC 时间 16:00 运行 (北京时间凌晨0点)
  schedule:
    - cron: "0 16 * * *"
  # 同样保留手动触发，方便测试
  workflow_dispatch:

jobs:
  daily-run-job:
    name: Fetch Yesterday's Papers
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            # 需要完整历史记录以便于读取和更新 daily.json
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 关键步骤：RUN_MODE 默认为 daily_run (由 Python 脚本处理)
      - name: Run Python script for daily update
        run: python daily_arxiv.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md daily.json
          git commit -m "Update daily arXiv papers" || echo "No changes to commit"
          git push
